# Generated by Django 5.2.17 on 2026-08-12 14:14

from django.db import migrations

def update_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building_year_from = 2015
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= new_building_year_from
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building_field),
    ]

