# Generated by Django 5.2.17 on 2026-08-13 13:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_liked_by_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Скорректированный номер владельца'),
        ),
    ]
