# Generated by Django 5.2.17 on 2026-08-13 13:27

from django.db import migrations
import phonenumbers

def remake_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if not phonenumbers.is_valid_number(phone_number):
            continue
        flat.owner_pure_phone = phonenumbers.format_number(
            phone_number, phonenumbers.PhoneNumberFormat.E164)
        flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(remake_phone_numbers, move_backward),
    ]
