# Generated by Django 5.2.17 on 2026-08-13 15:25

from django.db import migrations

def move_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phone_number': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone,
            },
        )
        owner.flats.add(flat)

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RunPython(move_owner_data, move_backward),
    ]
