# Generated by Django 5.2.17 on 2026-08-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_move_owners_data_20260813_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
